import type { ScreenConfig } from '@/lib/parity/screenConfigs'

export const storeInventoryLinks = [
  { label: 'Dashboard', href: '/store-inventory' },
  { label: 'Products', href: '/store-inventory/products' },
  { label: 'Create Product', href: '/store-inventory/product-create' },
  { label: 'Purchases', href: '/store-inventory/purchases' },
  { label: 'Create Purchase', href: '/store-inventory/purchase-create' },
  { label: 'Adjustments', href: '/store-inventory/adjustments' },
  { label: 'Create Adjustment', href: '/store-inventory/adjustment-create' },
  { label: 'Inventories', href: '/store-inventory/inventories' },
  { label: 'Inventory Assignments', href: '/store-inventory/inventory-assignments' },
  { label: 'Employee Assignments', href: '/store-inventory/employee-assignments' },
  { label: 'Demand Send', href: '/store-inventory/demands-send' },
  { label: 'Demand Response', href: '/store-inventory/demands-response' },
  { label: 'Stores', href: '/store-inventory/stores' },
  { label: 'Vendors', href: '/store-inventory/vendors' },
  { label: 'Weapons', href: '/store-inventory/weapons' },
  { label: 'Brands', href: '/store-inventory/brands' },
  { label: 'Units', href: '/store-inventory/units' },
  { label: 'Categories', href: '/store-inventory/categories' },
  { label: 'Conditions', href: '/store-inventory/conditions' },
  { label: 'Calibres', href: '/store-inventory/calibres' },
  { label: 'Licenses', href: '/store-inventory/licenses' },
  { label: 'Variations', href: '/store-inventory/variations' },
  { label: 'Statuses', href: '/store-inventory/statuses' },
  { label: 'Repairings', href: '/store-inventory/repairings' },
  { label: 'Product Unique Items', href: '/store-inventory/product-unique-items' },
  { label: 'Audits', href: '/store-inventory/audits' },
  { label: 'Roles', href: '/store-inventory/roles' },
  { label: 'Users', href: '/store-inventory/users' },
]

export const storeInventoryScreens: Record<string, ScreenConfig> = {
  products: {
    title: 'Products',
    description: 'Store inventory products listing and management.',
    actions: ['Search', 'Export'],
    table: { columns: ['Sr#', 'Product Name', 'Category', 'Brand', 'Unit', 'Status', 'Action'] },
  },
  'product-create': {
    title: 'Create Product',
    sections: [{
      title: 'Product Form',
      fields: [
        { label: 'Product Name', required: true },
        { label: 'Category', type: 'select', required: true },
        { label: 'Brand', type: 'select' },
        { label: 'Unit', type: 'select' },
        { label: 'Status', type: 'select' },
      ],
    }],
    actions: ['Save Product', 'Reset'],
  },
  purchases: {
    title: 'Purchases',
    actions: ['Search', 'Export'],
    table: { columns: ['Sr#', 'Store', 'Vendor', 'Total Qty', 'Date', 'User', 'Action'] },
  },
  'purchase-create': {
    title: 'Create Purchase',
    sections: [{ title: 'Purchase Entry', fields: [
      { label: 'Store', type: 'select', required: true },
      { label: 'Vendor', type: 'select', required: true },
      { label: 'Product', type: 'select', required: true },
      { label: 'Quantity', type: 'number', required: true },
      { label: 'Note', type: 'textarea' },
    ] }],
    actions: ['Add Purchase', 'Reset'],
  },
  adjustments: {
    title: 'Adjustments',
    actions: ['Search', 'Export'],
    table: { columns: ['Sr#', 'Store', 'Total Qty', 'Items', 'Date', 'User', 'Action'] },
  },
  'adjustment-create': {
    title: 'Create Adjustment',
    sections: [{ title: 'Adjustment Entry', fields: [
      { label: 'Store', type: 'select', required: true },
      { label: 'Product', type: 'select', required: true },
      { label: 'Quantity', type: 'number', required: true },
      { label: 'Condition', type: 'select' },
      { label: 'Note', type: 'textarea' },
    ] }],
    actions: ['Add Adjustment', 'Reset'],
  },
  inventories: {
    title: 'Inventories',
    table: { columns: ['Sr#', 'Store', 'Product', 'Total Qty', 'Available Qty', 'Assigned Qty', 'Action'] },
    actions: ['Search', 'Export'],
  },
  'inventory-assignments': {
    title: 'Inventory Assignments',
    table: { columns: ['Sr#', 'Store', 'Guard ID', 'Guard Name', 'Product', 'Assigned At', 'Status', 'Action'] },
    actions: ['Search', 'Export'],
  },
  'employee-assignments': {
    title: 'Employee Inventory Assignments',
    table: { columns: ['Sr#', 'Employee ID', 'Employee Name', 'Product', 'Assigned By', 'Assigned At', 'Status'] },
    actions: ['Search', 'Clear Filters'],
  },
  'demands-send': {
    title: 'Demands Send',
    table: { columns: ['Sr#', 'From Store', 'To Store', 'Requested By', 'Date', 'Total Required Qty', 'Status', 'Action'] },
    actions: ['Search', 'Create Demand'],
  },
  'demands-response': {
    title: 'Demands Response',
    table: { columns: ['Sr#', 'Demand Ref', 'Responder', 'Date', 'Status', 'Action'] },
    actions: ['Search', 'Respond'],
  },
  stores: {
    title: 'Stores',
    table: { columns: ['Warehouse Name', 'Region', 'Prefix', 'Store', 'Landline', 'Mobile', 'Address', 'Action'] },
    actions: ['Create New', 'Update', 'Export'],
  },
  brands: { title: 'Brands', table: { columns: ['Name', 'Action'] }, actions: ['Create', 'Update', 'Delete'] },
  units: { title: 'Units', table: { columns: ['Name', 'Action'] }, actions: ['Create', 'Update', 'Delete'] },
  categories: { title: 'Categories', table: { columns: ['Name', 'Action'] }, actions: ['Create', 'Update', 'Delete'] },
  conditions: { title: 'Conditions', table: { columns: ['Name', 'Action'] }, actions: ['Create', 'Update', 'Delete'] },
  weapons: { title: 'Weapons', table: { columns: ['Name', 'Action'] }, actions: ['Create', 'Update', 'Delete'] },
  'weapon-types': { title: 'Weapon Types', table: { columns: ['Name', 'Action'] }, actions: ['Create', 'Update', 'Delete'] },
  calibres: { title: 'Calibres', table: { columns: ['Name', 'Action'] }, actions: ['Create', 'Update', 'Delete'] },
  licenses: { title: 'Licenses', table: { columns: ['Name', 'Action'] }, actions: ['Create', 'Update', 'Delete'] },
  variations: { title: 'Variations', table: { columns: ['Name', 'Action'] }, actions: ['Create', 'Update', 'Delete'] },
  statuses: { title: 'Statuses', table: { columns: ['Name', 'Action'] }, actions: ['Create', 'Update', 'Delete'] },
  repairings: { title: 'Repairings', table: { columns: ['Name', 'Action'] }, actions: ['Create', 'Update', 'Delete'] },
  'product-unique-items': {
    title: 'Product Unique Items',
    table: { columns: ['Sr#', 'Product', 'Unique Number', 'Serial Number', 'Status', 'Action'] },
    actions: ['Search', 'Export'],
  },
  audits: {
    title: 'Audits',
    table: { columns: ['Sr#', 'User', 'Model', 'Model ID', 'Event', 'IP', 'Date', 'Action'] },
    actions: ['Search', 'Clear'],
  },
  roles: { title: 'Roles', table: { columns: ['Sr#', 'Role Name', 'Action'] }, actions: ['Create Role'] },
  users: { title: 'Users', table: { columns: ['Sr#', 'Name', 'Email', 'Role', 'Stores/Warehouse', 'Action'] }, actions: ['Create User'] },
}
