import { auth } from "@/lib/auth"
import { redirect, notFound } from "next/navigation"
import { prisma } from "@/lib/db"
import { deriveManagerScope, managerScopeDenied } from "@/lib/access/scope"
import { hasAction, isSuperAdmin } from "@/lib/api/permissions"
import Link from "next/link"
import { ArrowLeft, Edit, AlertTriangle, CheckCircle, XCircle } from "lucide-react"
import GuardProfileTabs from "@/components/guards/GuardProfileTabs"
import ProfileImageCard from "@/components/guards/ProfileImageCard"
import GuardProfileHealth from "@/components/guards/GuardProfileHealth"
import MentalHealthBadge from "@/components/guards/MentalHealthBadge"
import GuardLifecycleProgress from "@/components/guards/GuardLifecycleProgress"
import GuardStatusSupervisorEditor from "@/components/guards/GuardStatusSupervisorEditor"
import InlineAlert from "@/components/ui/inline-alert"
import { isPrismaMissingSchemaError, toErrorMessage } from "@/lib/prisma-errors"
import type { GuardTabModel, NearestRelative } from "@/components/guards/tabs/types"

type GuardDetailModel = GuardTabModel & {
    id: string
    parwestId: string
    name: string
    cnic: string
    phone?: string | null
    email?: string | null
    status: string
    photoUrl?: string | null
    regionalOffice?: { name?: string | null } | null
    managerName?: string | null
    joiningAge?: number | null
    enrolledBy?: string | null
    profileIntroducer?: string | null
    nearestRelatives?: NearestRelative[]
    attendanceRecords?: Array<{
        id: string; date: Date; status: string; shiftType: string | null
        attendanceType: string | null; clientId: string | null; clientName: string | null
        hoursWorked: number | null; overtimeHours: number | null; notes: string | null
        deploymentId: string | null; isAutoGenerated: boolean
    }>
    deploymentRecords?: Array<{
        id: string; status: string; designation: string; shiftType: string
        deploymentDate: Date; endDate: Date | null; endReason: string | null
        salary: number | null; deploymentNature: string | null; deploymentType: string | null
        deployedByName: string | null; revokedByName: string | null
        client: { id: string; name: string }
        branch: { id: string; name: string; city: string | null } | null
        regionalOffice: { id: string; name: string }
    }>
    storeInventoryAssignments?: Array<Record<string, unknown>>
    verificationDocTypes?: Array<{ name: string }>
    verificationPrerequisites?: Array<{ docTypeName: string; status: string }>
    residenceAssignments?: Array<{
        id: string
        location: string
        status: string
        assignedAt: Date | string
        assignedByName: string | null
        vacatedAt: Date | string | null
        vacatedByName: string | null
        vacatedReason: string | null
        notes: string | null
        residence: {
            id: string
            address: string
            supervisor: string | null
            city: string | null
            state: string | null
        } | null
    }>
}

function toDateOrNull(value?: Date | string | null) {
    if (!value) return null
    const parsed = value instanceof Date ? value : new Date(value)
    return Number.isNaN(parsed.getTime()) ? null : parsed
}

function calculateAge(dateOfBirth?: Date | string | null, referenceDate?: Date | string | null) {
    const birthDate = toDateOrNull(dateOfBirth)
    const joinedDate = toDateOrNull(referenceDate)
    if (!birthDate || !joinedDate) return null
    let years = joinedDate.getFullYear() - birthDate.getFullYear()
    const monthDiff = joinedDate.getMonth() - birthDate.getMonth()
    if (monthDiff < 0 || (monthDiff === 0 && joinedDate.getDate() < birthDate.getDate())) {
        years--
    }
    return years >= 0 ? years : null
}

function formatShortDate(value?: Date | string | null) {
    if (!value) return null
    const parsed = value instanceof Date ? value : new Date(value)
    if (Number.isNaN(parsed.getTime())) return null
    return parsed.toLocaleDateString("en-US", { year: "numeric", month: "short", day: "numeric" })
}

export default async function GuardDetailPage({ params }: { params: Promise<{ id: string }> }) {
    const session = await auth()
    if (!session) redirect("/login")

    const canCreateGuard = hasAction(session, "GUARDS", "CREATE")
    const canUpdateGuard = hasAction(session, "GUARDS", "UPDATE")
    const canDeleteGuard = hasAction(session, "GUARDS", "DELETE")

    const { id } = await params
    const managerScope = deriveManagerScope(session)

    let dbWarning = ""
    let guard: GuardDetailModel | null = null

    try {
        const [
            guardData,
            activeSupervisor,
            attendanceRecords,
            deploymentRecords,
            storeInventoryAssignments,
            verificationDocTypes,
            verificationPrerequisites,
            residenceAssignments,
        ] = await Promise.all([
            prisma.guard.findUnique({
                where: { id },
                include: {
                    region: true,
                    regionalOffice: true,
                },
            }),
            prisma.guardSupervisorAssignment.findFirst({
                where: { guardId: id, status: "ACTIVE" },
                include: { supervisor: { select: { name: true } } },
            }),
            prisma.attendance.findMany({
                where: { guardId: id },
                orderBy: { date: "desc" },
                take: 365,
            }).catch(() => []),
            prisma.deployment.findMany({
                where: { guardId: id },
                orderBy: { deploymentDate: "desc" },
                include: {
                    client: { select: { id: true, name: true } },
                    branch: { select: { id: true, name: true, city: true } },
                    regionalOffice: { select: { id: true, name: true } },
                },
            }).catch(() => []),
            prisma.storeInventoryAssignment.findMany({
                where: { assignedToGuardId: id },
                orderBy: { assignedAt: "desc" },
                include: {
                    product: { include: { variation: { select: { name: true } } } },
                    condition: { select: { name: true } },
                    returnCondition: { select: { name: true } },
                    assignedByUser: { select: { name: true } },
                    returnedByUser: { select: { name: true } },
                },
            }).catch(() => []),
            prisma.guardDocumentType.findMany({
                where: { isActive: true, docCategory: "VERIFICATION" },
                select: { name: true },
            }).catch(() => []),
            prisma.guardPrerequisite.findMany({
                where: { guardId: id },
                select: { docTypeName: true, status: true },
            }).catch(() => []),
            prisma.residenceAssignment.findMany({
                where: { guardId: id },
                orderBy: { assignedAt: "desc" },
                include: {
                    residence: {
                        select: {
                            id: true,
                            address: true,
                            supervisor: true,
                            city: true,
                            state: true,
                        },
                    },
                },
            }).catch(() => []),
        ])
        if (guardData && managerScope && managerScopeDenied(managerScope, {
            regionId: guardData.regionId,
            regionalOfficeId: guardData.regionalOfficeId,
        })) {
            notFound()
        }

        guard = guardData
            ? {
                ...guardData,
                managerName: activeSupervisor?.supervisor?.name ?? null,
                attendanceRecords,
                deploymentRecords,
                storeInventoryAssignments,
                verificationDocTypes,
                verificationPrerequisites,
                residenceAssignments,
            }
            : null
    } catch (error) {
        if (!isPrismaMissingSchemaError(error)) {
            throw error
        }
        dbWarning = `Database schema is not fully migrated (${toErrorMessage(
            error,
            "missing required tables"
        )}). Guard profile is unavailable.`
        console.error("GuardDetailPage query failed:", error)
    }

    if (!guard) {
        if (dbWarning) {
            return (
                <div className="space-y-6">
                    <InlineAlert type="error" message={dbWarning} />
                    <div className="ui-card p-6 space-y-4">
                        <h1 className="text-2xl font-semibold text-[var(--text)]">Guard profile unavailable</h1>
                        <p className="text-sm text-[var(--text-muted)]">
                            Guard detail could not be loaded because required database schema is unavailable.
                        </p>
                        <Link href="/guards" className="ui-btn ui-btn-secondary inline-flex items-center gap-2">
                            <ArrowLeft className="h-4 w-4" />
                            Back to Guards
                        </Link>
                    </div>
                </div>
            )
        }
        notFound()
    }

    const parseJson = (raw: unknown): unknown[] => {
        try {
            if (typeof raw === "string" && raw) return JSON.parse(raw)
        } catch { /* ignore */ }
        return Array.isArray(raw) ? raw : []
    }

    const g = guard as Record<string, unknown>
    const rawAttendance = guard.attendanceRecords ?? []
    const rawDeployments = guard.deploymentRecords ?? []
    const rawStoreInventory = (g.storeInventoryAssignments as Array<Record<string, unknown>> | undefined) ?? []
    const verificationDocTypes = (g.verificationDocTypes as Array<{ name: string }> | undefined) ?? []
    const verificationPrerequisites =
        (g.verificationPrerequisites as Array<{ docTypeName: string; status: string }> | undefined) ?? []

    // Build attendance summary
    const presentCount = rawAttendance.filter((a) => a.status === "PRESENT").length
    const absentCount  = rawAttendance.filter((a) => a.status === "ABSENT").length
    const totalOT      = rawAttendance.reduce((s, a) => s + (a.overtimeHours ?? 0), 0)
    const verificationTotal = verificationDocTypes.length
    const verificationStatusByDoc = new Map(verificationPrerequisites.map((row) => [row.docTypeName, row.status]))
    const verificationVerified = verificationDocTypes.filter((row) => verificationStatusByDoc.get(row.name) === "VERIFIED").length
    const assignedInventoryCount = rawStoreInventory.filter((row) => row.status === "ASSIGNED").length
    const activeDeploymentsCount = rawDeployments.filter((row) => row.status === "ACTIVE").length
    const revokedDeploymentsCount = rawDeployments.filter((row) => row.status === "INACTIVE" || row.endDate).length
    const currentDeployment = rawDeployments.find((row) => row.status === "ACTIVE")
    const latestEndedDeployment = rawDeployments.find((row) => row.status === "INACTIVE" || row.endDate)

    const guardWithTabs = {
        ...guard,
        regionalOffice: guard.regionalOffice?.name || null,
        managerName: guard.managerName || "—",
        joiningAge: guard.joiningAge ?? calculateAge(guard.dateOfBirth ?? null, guard.joiningDate ?? null) ?? null,
        enrolledBy: guard.enrolledBy || "—",
        profileIntroducer: guard.profileIntroducer || "—",
        nearestRelatives: parseJson(g.nearestRelativesJson) as NearestRelative[],
        familyMembers: parseJson(g.familyMembersJson) as Record<string, unknown>[],
        previousEmployments: parseJson(g.previousEmploymentsJson) as Record<string, unknown>[],
        bankDetails: {
            bankName: g.bankName as string | null,
            accountNumber: g.bankAccountNumber as string | null,
            accountType: g.bankAccountType as string | null,
            iban: g.bankIban as string | null,
            branchCode: g.bankBranchCode as string | null,
            bankAccountsJson: g.bankAccountsJson as string | null,
        },
        // Real attendance data
        attendance: rawAttendance.map((a) => ({
            date: a.date,
            status: a.status,
            shift: a.shiftType ?? undefined,
            attendanceType: a.attendanceType ?? "PRESENT",
            clientId: a.clientId ?? undefined,
            clientName: a.clientName ?? undefined,
            hours: a.hoursWorked ?? undefined,
            overtime: a.overtimeHours ?? undefined,
            reason: a.notes ?? undefined,
            deploymentId: a.deploymentId ?? undefined,
            isAutoGenerated: a.isAutoGenerated,
        })),
        attendanceSummary: {
            totalDays: rawAttendance.length,
            present: presentCount,
            absent: absentCount,
            overtime: Math.round(totalOT * 10) / 10,
        },
        // Store inventory history
        storeInventory: rawStoreInventory.map((a) => {
            const product = a.product as Record<string, unknown> | null
            const variation = product?.variation as Record<string, unknown> | null
            const condition = a.condition as Record<string, unknown> | null
            const returnCondition = a.returnCondition as Record<string, unknown> | null
            const assignedByUser = a.assignedByUser as Record<string, unknown> | null
            const returnedByUser = a.returnedByUser as Record<string, unknown> | null
            return {
                id: a.id,
                productName: product?.name ?? null,
                productSku: product?.sku ?? null,
                productVariation: variation?.name ?? null,
                assignedAt: a.assignedAt,
                conditionName: condition?.name ?? null,
                assignedByName: assignedByUser?.name ?? null,
                returnedAt: a.returnedAt,
                returnConditionName: returnCondition?.name ?? null,
                returnedByName: returnedByUser?.name ?? null,
                status: a.status,
                quantity: a.quantity,
            }
        }),
        // Real deployment history — shape matches DeploymentAuditRecord for AttendanceTab
        deployments: rawDeployments.map((d) => ({
            id: d.id,
            status: d.status,
            shiftType: d.shiftType,
            designation: d.designation,
            deploymentDate: d.deploymentDate,
            endDate: d.endDate ?? null,
            endReason: d.endReason ?? null,
            deploymentType: d.deploymentType ?? null,
            deploymentNature: d.deploymentNature ?? null,
            deployedByName: (d as Record<string, unknown>).deployedByName as string | null ?? null,
            revokedByName: (d as Record<string, unknown>).revokedByName as string | null ?? null,
            client: d.client,
            branch: d.branch ?? null,
            regionalOffice: d.regionalOffice,
            // Legacy flat fields for DeploymentHistoryTab
            clientName: d.client.name,
            clientId: d.client.id,
            branchName: d.branch?.name ?? null,
            branchCity: d.branch?.city ?? null,
            salary: d.salary ?? null,
            regionalOfficeName: d.regionalOffice.name,
        })),
        // Residence assignment history
        residenceHistory: ((g.residenceAssignments ?? []) as Array<Record<string, unknown>>).map((ra) => {
            const residence = ra.residence as Record<string, unknown> | null | undefined
            return {
                id: ra.id,
                address: (residence?.address as string | null | undefined) ?? (ra.location as string | null | undefined),
                status: ra.status === "ACTIVE" ? "CURRENT" : "VACATED",
                supervisor: (residence?.supervisor as string | null | undefined) ?? null,
                city: (residence?.city as string | null | undefined) ?? null,
                state: (residence?.state as string | null | undefined) ?? null,
                assignDate: ra.assignedAt,
                assignedByName: (ra.assignedByName as string | null | undefined) ?? null,
                vacateDate: (ra.vacatedAt as string | Date | null | undefined) ?? null,
                vacatedByName: (ra.vacatedByName as string | null | undefined) ?? null,
                vacatedReason: (ra.vacatedReason as string | null | undefined) ?? null,
                notes: (ra.notes as string | null | undefined) ?? null,
            }
        }),
    }

    return (
        <div className="space-y-6">
            {dbWarning ? <InlineAlert type="error" message={dbWarning} /> : null}

            {/* Header */}
            <div className="flex items-center justify-between">
                <div className="flex items-center gap-4">
                    <Link
                        href="/guards"
                        className="flex items-center gap-2 text-gray-600 hover:text-gray-900"
                    >
                        <ArrowLeft className="h-5 w-5" />
                        Back to Guards
                    </Link>
                </div>
                {canUpdateGuard ? (
                    <Link
                        href={`/guards/${guard.id}/edit`}
                        className="flex items-center gap-2 bg-blue-600 text-white px-4 py-2 rounded-md hover:bg-blue-700"
                    >
                        <Edit className="h-4 w-4" />
                        Edit Guard
                    </Link>
                ) : null}
            </div>

            <div className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_320px]">
            {/* Guard Header Card */}
            <div className="bg-white rounded-lg border p-6">
                <div className="flex items-start justify-between">
                    <div>
                        <h1 className="text-3xl font-bold">{guard.name}</h1>
                        <p className="text-gray-600 mt-1">Parwest ID: {guard.parwestId}</p>
                        {/* Age approval flag */}
                        {!!(guard as Record<string, unknown>).ageApprovalRequired && (
                            <div className="mt-2">
                                {(guard as Record<string, unknown>).ageApprovalStatus === "PENDING" && (
                                    <span className="inline-flex items-center gap-1.5 rounded-full bg-orange-100 px-3 py-1 text-xs font-semibold text-orange-800 border border-orange-200">
                                        <AlertTriangle className="h-3.5 w-3.5" />
                                        Age Approval Pending
                                    </span>
                                )}
                                {(guard as Record<string, unknown>).ageApprovalStatus === "APPROVED" && (
                                    <span className="inline-flex items-center gap-1.5 rounded-full bg-green-100 px-3 py-1 text-xs font-semibold text-green-800 border border-green-200">
                                        <CheckCircle className="h-3.5 w-3.5" />
                                        Age Exception Approved
                                    </span>
                                )}
                                {(guard as Record<string, unknown>).ageApprovalStatus === "REJECTED" && (
                                    <span className="inline-flex items-center gap-1.5 rounded-full bg-red-100 px-3 py-1 text-xs font-semibold text-red-800 border border-red-200">
                                        <XCircle className="h-3.5 w-3.5" />
                                        Age Exception Rejected
                                    </span>
                                )}
                            </div>
                        )}
                        <div className="mt-4">
                            <GuardProfileHealth guard={guardWithTabs as Parameters<typeof GuardProfileHealth>[0]["guard"]} />
                        </div>
                        <GuardLifecycleProgress
                            guardStatus={guard.status}
                            verificationTotal={verificationTotal}
                            verificationVerified={verificationVerified}
                            assignedInventoryCount={assignedInventoryCount}
                            activeDeploymentsCount={activeDeploymentsCount}
                            revokedDeploymentsCount={revokedDeploymentsCount}
                            currentDeployment={
                                currentDeployment
                                    ? {
                                        clientName: currentDeployment.client?.name ?? "Unknown Client",
                                        branchName: currentDeployment.branch?.name ?? null,
                                        shiftType: currentDeployment.shiftType ?? null,
                                        designation: currentDeployment.designation ?? null,
                                        deploymentDate: formatShortDate(currentDeployment.deploymentDate),
                                    }
                                    : null
                            }
                            latestEndedDeployment={
                                !currentDeployment && latestEndedDeployment
                                    ? {
                                        clientName: latestEndedDeployment.client?.name ?? "Unknown Client",
                                        branchName: latestEndedDeployment.branch?.name ?? null,
                                        endDate: formatShortDate(latestEndedDeployment.endDate ?? null),
                                        endReason: latestEndedDeployment.endReason ?? null,
                                    }
                                    : null
                            }
                        />
                    </div>
                    <div className="flex flex-col items-end gap-2">
                        <GuardStatusSupervisorEditor
                            guardId={guard.id}
                            currentStatus={guard.status}
                            currentSupervisorName={guardWithTabs.managerName ?? null}
                            isSuperAdmin={isSuperAdmin(session)}
                            canUpdate={canUpdateGuard}
                            guardRegionId={(guard as { regionId?: string | null }).regionId ?? null}
                            guardRegionalOfficeId={(guard as { regionalOfficeId?: string | null }).regionalOfficeId ?? null}
                        />
                        <MentalHealthBadge guardId={guard.id} />
                    </div>
                </div>
            </div>
            <ProfileImageCard
                guardId={guard.id}
                guardName={guard.name}
                initialUrl={guard.photoUrl ?? null}
                canCreate={canCreateGuard}
            />
            </div>

            {/* Tabs */}
            <GuardProfileTabs
                guard={guardWithTabs}
                baseUrl={`/guards/${guard.id}`}
                canCreate={canCreateGuard}
                canUpdate={canUpdateGuard}
                canDelete={canDeleteGuard}
            />
        </div>
    )
}
