import type { UiSection, UiTable } from "@/components/parity/UiDocScreen"

export type ScreenConfig = {
  title: string
  description?: string
  tabs?: string[]
  sections?: UiSection[]
  table?: UiTable
  actions?: string[]
}

const payrollLoanSections: UiSection[] = [
  {
    title: "Add Loan",
    fields: [
      { label: "Month", type: "month", required: true },
      { label: "Parwest ID", required: true },
      { label: "Guard Name", required: true },
      { label: "Phone" },
      { label: "Client/Branch" },
      { label: "Deployment Days", type: "number" },
      { label: "Current Supervisor/Manager" },
      { label: "Amount Paid", type: "number", required: true },
    ],
  },
]

export const payrollOperationScreens: Record<string, ScreenConfig> = {
  loan: {
    title: "Payroll Loan",
    description: "Loan operations with add/finalize/export tabs.",
    tabs: ["Add Loans", "Finalize Loans", "Export Finalised History"],
    sections: payrollLoanSections,
    actions: ["Save Loan", "Finalize Selected", "Export Finalised History"],
    table: {
      title: "Loan Records",
      columns: ["Month", "Parwest ID", "Guard", "Client/Branch", "Amount", "Status", "Action"],
    },
  },
  "extra-hours": {
    title: "Extra Hours",
    sections: [
      {
        title: "Record Extra Hours",
        fields: [
          { label: "Parwest ID", required: true },
          { label: "Branch", required: true },
          { label: "Hours", type: "number", required: true },
          { label: "Creation Date", type: "date", required: true },
        ],
      },
    ],
    actions: ["Save Extra Hours"],
    table: { columns: ["Parwest ID", "Branch", "Hours", "Creation Date", "Action"] },
  },
  "other-deductions": {
    title: "Other Deductions",
    sections: [
      {
        title: "Record Miscellaneous Deductions",
        fields: [
          { label: "Parwest ID", required: true },
          { label: "Month", type: "month", required: true },
          { label: "Amount", type: "number", required: true },
          { label: "Reason", type: "textarea", required: true },
        ],
      },
    ],
    actions: ["Save Deduction"],
    table: { columns: ["Parwest ID", "Month", "Amount", "Reason", "Action"] },
  },
  "special-duty": {
    title: "Special Duty",
    sections: [
      {
        title: "Special Duty Record",
        fields: [
          { label: "Secure Ops ID", required: true },
          { label: "From Date", type: "date", required: true },
          { label: "To Date", type: "date", required: true },
          { label: "Hours", type: "number", required: true },
          { label: "Cost Per Hour", type: "number", required: true },
          { label: "Comments", type: "textarea" },
        ],
      },
    ],
    actions: ["Save Special Duty"],
    table: { columns: ["Secure Ops ID", "Date Range", "Hours", "Cost/Hour", "Comments", "Action"] },
  },
  holidays: {
    title: "Holidays",
    sections: [
      {
        title: "Holiday Calendar",
        fields: [
          { label: "Holiday Name", required: true },
          { label: "Date", type: "date", required: true },
          { label: "Notes", type: "textarea" },
        ],
      },
    ],
    actions: ["Add Holiday"],
    table: { columns: ["Holiday", "Date", "Notes", "Action"] },
  },
  salary: {
    title: "Calculate Salary",
    tabs: ["Calculate Salary", "Salary History"],
    sections: [
      {
        title: "Salary Filters",
        fields: [
          { label: "Region", type: "select", required: true },
          { label: "Select Client", type: "select" },
          { label: "Branch", type: "select" },
          { label: "Month", type: "month", required: true },
        ],
      },
    ],
    actions: ["Calculate Salary"],
    table: { columns: ["Parwest ID", "Guard", "Client/Branch", "Days", "Amount", "Status"] },
  },
  "salary-v1": {
    title: "Salary V1",
    sections: [{ title: "Legacy Salary View", fields: [{ label: "Month", type: "month" }, { label: "Region", type: "select" }] }],
    actions: ["Search"],
    table: { columns: ["Parwest ID", "Guard", "Net Salary", "Payment Status"] },
  },
  "salary-v2": {
    title: "Salary V2",
    sections: [{ title: "Salary V2 Filters", fields: [{ label: "Month", type: "month" }, { label: "Region", type: "select" }, { label: "Client", type: "select" }] }],
    actions: ["Search", "Export Summary"],
    table: { columns: ["Parwest ID", "Guard", "Base", "Deductions", "Net Salary", "Status"] },
  },
  "bulk-salary-slips": {
    title: "Bulk Salary Slips",
    sections: [{ title: "Mass Slip Generation", fields: [{ label: "Month", type: "month", required: true }, { label: "Region", type: "select" }, { label: "Client", type: "select" }] }],
    actions: ["Generate Slips", "Download Zip"],
    table: { columns: ["Cycle", "Employees", "Generated At", "Generated By", "Action"] },
  },
  clearance: {
    title: "Clearance",
    sections: [{ title: "Final Settlement", fields: [{ label: "Parwest ID" }, { label: "Last Working Date", type: "date" }, { label: "Pending Dues", type: "number" }, { label: "Notes", type: "textarea" }] }],
    actions: ["Process Clearance"],
    table: { columns: ["Parwest ID", "Name", "Final Amount", "Status", "Action"] },
  },
  "unpaid-salaries": {
    title: "UnPaid Salaries",
    sections: [{ title: "Unpaid Salary Filters", fields: [{ label: "Month", type: "month" }, { label: "Region", type: "select" }, { label: "Client", type: "select" }] }],
    actions: ["Search", "Export Unpaid Report"],
    table: { columns: ["Parwest ID", "Guard", "Month", "Amount", "Reason", "Action"] },
  },
}

export const inventoryScreens: Record<string, ScreenConfig> = {
  search: {
    title: "Inventory Search",
    description: "Central management hub for inventory.",
    sections: [
      {
        title: "Filters",
        fields: [
          { label: "Category", type: "select" },
          { label: "Product Type", type: "select" },
          { label: "Status", type: "select" },
          { label: "Vendor", type: "select" },
          { label: "Unique Number" },
          { label: "Serial Number" },
          { label: "Purchase Date From", type: "date" },
          { label: "Purchase Date To", type: "date" },
          { label: "Price", type: "number" },
          { label: "License Details" },
          { label: "Size" },
          { label: "Insured", type: "checkbox" },
          { label: "Duplicate", type: "checkbox" },
        ],
      },
    ],
    actions: ["Search", "Export In Excel File"],
    table: { columns: ["Category", "Item", "PPS #", "Secure Ops Number", "Vendor", "Status", "License Number", "Serial Number"] },
  },
  categories: {
    title: "Define Categories",
    sections: [{ title: "Category", fields: [{ label: "Category Name", placeholder: "WEAPON / UNIFORM / EQUIPMENT / AMMUNITION" }] }],
    actions: ["Create", "Update", "Delete"],
    table: { columns: ["Name", "Created At", "Action"] },
  },
  vendors: {
    title: "Define Vendors",
    sections: [{ title: "Vendor", fields: [{ label: "Vendor Name" }, { label: "Contact" }] }],
    actions: ["Create", "Update", "Delete"],
    table: { columns: ["Name", "Contact", "Action"] },
  },
  conditions: {
    title: "Define Conditions",
    sections: [{ title: "Condition", fields: [{ label: "Condition Name", placeholder: "NEW / OLD" }] }],
    actions: ["Create", "Update", "Delete"],
    table: { columns: ["Condition", "Action"] },
  },
  demand: {
    title: "Inventory Demand",
    sections: [{ title: "Demand Request", fields: [{ label: "Regional Office", type: "select" }, { label: "Category", type: "select" }, { label: "Item", type: "select" }, { label: "Requested Quantity", type: "number" }, { label: "Notes", type: "textarea" }] }],
    actions: ["Checkout", "Track Requests"],
    table: { columns: ["Request ID", "Regional Office", "Category", "Item", "Requested", "Fulfilled", "Status"] },
  },
  "stock-in": {
    title: "Stock In",
    sections: [{ title: "Register New Inventory", fields: [{ label: "Order ID" }, { label: "Category", type: "select" }, { label: "Item", type: "select" }, { label: "Vendor", type: "select" }, { label: "Price", type: "number" }, { label: "Purchase Date", type: "date" }, { label: "Date of Expiry", type: "date" }, { label: "Warranty Time" }, { label: "Warranty Type" }, { label: "Size" }, { label: "Weight" }, { label: "Length" }, { label: "Width" }, { label: "Color" }, { label: "Is Insured", type: "checkbox" }, { label: "Is Non Unique", type: "checkbox" }, { label: "Quantity of Non Unique Items", type: "number" }] }],
    actions: ["Save Stock In"],
  },
  "assign-item": {
    title: "Assign Item",
    sections: [{ title: "Assign Inventory", fields: [{ label: "Assign To", type: "select", options: ["Client", "Guard"] }, { label: "Select Regional Office", type: "select" }, { label: "Select Category", type: "select" }, { label: "Select Client/Guard", type: "select" }, { label: "Secure Ops Unique Number" }, { label: "Serial Number" }] }],
    actions: ["Checkout"],
    table: { columns: ["Item", "Assigned To", "Assigned At", "Returned At", "Status"] },
  },
  condemned: {
    title: "Condemned Items",
    sections: [{ title: "Condemn Item", fields: [{ label: "Unique ID" }, { label: "Condemned Date", type: "date" }, { label: "Reason", type: "textarea" }] }],
    actions: ["Mark as Condemned"],
    table: { columns: ["Unique ID", "Product Type", "Category", "Vendor", "Regional Office", "Purchase Date", "Condemned Date"] },
  },
}

export const reportScreens: Record<string, ScreenConfig> = {
  scheduled: {
    title: "Scheduled Reports",
    sections: [{ title: "Schedule Configuration", fields: [{ label: "Report Type", type: "select" }, { label: "Frequency", type: "select" }, { label: "Region", type: "select" }, { label: "Recipient Email addresses", type: "textarea" }] }],
    actions: ["Save Schedule"],
    table: { columns: ["Report Type", "Frequency", "Region", "Recipients", "Status", "Action"] },
  },
  "guard-deployment": {
    title: "Guard Deployment Report",
    sections: [{ title: "Filters", fields: [{ label: "Start Date", type: "date" }, { label: "End Date", type: "date" }, { label: "Regional Offices", type: "select" }, { label: "Client Types", type: "select" }, { label: "Specific Clients", type: "select" }] }],
    actions: ["Generate Report", "Export"],
  },
  "day-night-duty": {
    title: "Day and Night Duty Guards",
    sections: [{ title: "Filters", fields: [{ label: "Date From", type: "date" }, { label: "Date To", type: "date" }, { label: "Regional Office", type: "select" }, { label: "Client Type", type: "select" }, { label: "Client", type: "select" }, { label: "Report Type", type: "select", options: ["Day", "Night", "Both"] }] }],
    actions: ["Generate Report", "Export"],
  },
  "client-enrolled": {
    title: "Client Enrolled Report",
    sections: [{ title: "Filters", fields: [{ label: "Start Date", type: "date" }, { label: "End Date", type: "date" }, { label: "Regional Offices", type: "select" }, { label: "Branch Types", type: "select" }] }],
    actions: ["Generate Report", "Export"],
  },
}

export const importScreens: Record<string, ScreenConfig> = {
  users: {
    title: "Users Import",
    sections: [{ title: "Upload User File", fields: [{ label: "Name" }, { label: "Secure Ops Domain Email", type: "email" }, { label: "User Role", type: "select" }, { label: "Regional Office Series" }, { label: "Contact Number" }] }],
    actions: ["Choose File", "Validate", "Import"],
    table: { columns: ["Row", "Name", "Email", "Role", "Result"] },
  },
  guards: {
    title: "Guards Import",
    tabs: ["Registration", "Verification", "Training", "Experience", "Family", "Placement", "References"],
    sections: [{ title: "Upload Guard File", fields: [{ label: "Import Type", type: "select" }, { label: "Upload File" }] }],
    actions: ["Validate", "Import"],
    table: { columns: ["Row", "Guard", "Type", "Result"] },
  },
  clients: {
    title: "Clients Import",
    sections: [{ title: "Bulk Client/Branch Upload", fields: [{ label: "Upload File" }] }],
    actions: ["Validate", "Import"],
    table: { columns: ["Row", "Client", "Branch", "Result"] },
  },
  inventory: {
    title: "Inventory Import",
    sections: [{ title: "Bulk Inventory Upload", fields: [{ label: "Upload File" }] }],
    actions: ["Validate", "Import"],
    table: { columns: ["Row", "Item", "Category", "Result"] },
  },
}

export const payrollReportExports = [
  "Export Bank Salary",
  "Export Cash Salary",
  "Bank Transfer Sheet",
  "Mobile Account",
  "EOBI List",
  "EOBI Export",
  "ESSI List",
  "ESSI Export",
  "Salary Summary Report",
  "Region-wise Report",
  "Salary Detail Report",
  "Unpaid Salary Report",
]

export const payrollOperationLinks = [
  { label: "Loan", href: "/payroll/operations/loan" },
  { label: "Extra Hours", href: "/payroll/operations/extra-hours" },
  { label: "Other Deductions", href: "/payroll/operations/other-deductions" },
  { label: "Special Duty", href: "/payroll/operations/special-duty" },
  { label: "Holidays", href: "/payroll/operations/holidays" },
  { label: "Salary", href: "/payroll/operations/salary-v2" },
  { label: "Bulk Slips", href: "/payroll/operations/bulk-salary-slips" },
  { label: "Clearance", href: "/payroll/operations/clearance" },
  { label: "UnPaid", href: "/payroll/operations/unpaid-salaries" },
]

export const inventoryLinks = [
  { label: "Search", href: "/inventory/search" },
  { label: "Categories", href: "/inventory/categories" },
  { label: "Vendors", href: "/inventory/vendors" },
  { label: "Conditions", href: "/inventory/conditions" },
  { label: "Demand", href: "/inventory/demand" },
  { label: "Stock In", href: "/inventory/stock-in" },
  { label: "Assign Item", href: "/inventory/assign-item" },
  { label: "Condemned", href: "/inventory/condemned" },
]

export const reportLinks = [
  { label: "Overview", href: "/reports" },
  { label: "Scheduled", href: "/reports/scheduled" },
  { label: "Guard Deployment", href: "/reports/guard-deployment" },
  { label: "Day & Night", href: "/reports/day-night-duty" },
  { label: "Client Enrolled", href: "/reports/client-enrolled" },
  { label: "AI/Prompt", href: "/reports/ai" },
  { label: "Generated List", href: "/reports/generated" },
]

export const importLinks = [
  { label: "Users Import", href: "/imports/users" },
  { label: "Guards Import", href: "/imports/guards" },
  { label: "Clients Import", href: "/imports/clients" },
  { label: "Inventory Import", href: "/imports/inventory" },
]

export const dashboardScreens: Record<string, ScreenConfig> = {
  "online-users": {
    title: "Online Users",
    description: "Current active users with filters and session activity snapshot.",
    sections: [
      {
        title: "Online User Filters",
        fields: [
          { label: "Regional Office", type: "select" },
          { label: "Role", type: "select" },
          { label: "User Name" },
          { label: "Last Activity From", type: "date" },
          { label: "Last Activity To", type: "date" },
        ],
      },
    ],
    actions: ["Search", "Clear", "Export In Excel"],
    table: { columns: ["User", "Role", "Regional Office", "IP Address", "Last Activity", "Session ID"] },
  },
}

export const userScreens: Record<string, ScreenConfig> = {
  new: {
    title: "Add New User",
    description: "User enrolment form from UI docs.",
    sections: [
      {
        title: "User Enrolment",
        fields: [
          { label: "User's Name", required: true },
          { label: "Email", type: "email", required: true },
          { label: "User Role", type: "select", required: true },
          { label: "Select Region", type: "select" },
          { label: "Regional Office", type: "select" },
          { label: "Contact #", required: true },
          { label: "Password", required: true },
          { label: "Status", type: "select", options: ["Active", "Inactive"] },
        ],
      },
    ],
    actions: ["Submit", "Reset"],
    table: { columns: ["Name", "Email", "Role", "Regional Office", "Status"] },
  },
  search: {
    title: "Search Users",
    sections: [
      {
        title: "Filters",
        fields: [
          { label: "Name" },
          { label: "Email" },
          { label: "User Role", type: "select" },
          { label: "Regional Office", type: "select" },
          { label: "Status", type: "select" },
        ],
      },
    ],
    actions: ["Search", "Clear", "Export in Excel"],
    table: { columns: ["ID", "Photo", "Name", "Email", "Role", "Regional Office", "Status", "Action"] },
  },
  "ms-relationship": {
    title: "M/S Relationship",
    description: "Assign managers to supervisors.",
    sections: [
      {
        title: "Assign Relationship",
        fields: [
          { label: "Manager", type: "select", required: true },
          { label: "Supervisor", type: "select", required: true },
          { label: "Effective Date", type: "date" },
          { label: "Notes", type: "textarea" },
        ],
      },
    ],
    actions: ["Assign", "Clear"],
    table: { columns: ["Manager", "Supervisor", "Effective Date", "Status", "Action"] },
  },
  "cs-relationship": {
    title: "C/S Relationship",
    description: "Assign client branches to supervisors.",
    sections: [
      {
        title: "Assign Client Branch",
        fields: [
          { label: "Client", type: "select", required: true },
          { label: "Branch", type: "select", required: true },
          { label: "Supervisor", type: "select", required: true },
          { label: "Effective Date", type: "date" },
          { label: "Notes", type: "textarea" },
        ],
      },
    ],
    actions: ["Assign", "Clear"],
    table: { columns: ["Client", "Branch", "Supervisor", "Effective Date", "Status", "Action"] },
  },
  "switch-supervisor": {
    title: "Switch Supervisor",
    description: "Bulk transfer supervisors between managers or locations.",
    sections: [
      {
        title: "Switch Tool",
        fields: [
          { label: "From Supervisor", type: "select", required: true },
          { label: "To Supervisor", type: "select", required: true },
          { label: "Region", type: "select" },
          { label: "Regional Office", type: "select" },
          { label: "Reason", type: "textarea" },
        ],
      },
    ],
    actions: ["Preview", "Switch", "Clear"],
    table: { columns: ["From Supervisor", "To Supervisor", "Region", "Regional Office", "Result"] },
  },
}

export const userLinks = [
  { label: "Add New", href: "/users/new" },
  { label: "Search", href: "/users/search" },
  { label: "Permissions", href: "/users/permissions" },
  { label: "M/S Relationship", href: "/users/ms-relationship" },
  { label: "Switch Supervisor", href: "/users/switch-supervisor" },
  { label: "C/S Relationship", href: "/users/cs-relationship" },
]

export const ticketScreens: Record<string, ScreenConfig> = {
  listing: {
    title: "Ticketing Listing",
    description: "All tickets listing with documented filters and columns.",
    sections: [
      {
        title: "Search Filters",
        fields: [
          { label: "Category", type: "select" },
          { label: "Priority", type: "select" },
          { label: "Status", type: "select" },
          { label: "Supervisor", type: "select" },
          { label: "Created Date", type: "date" },
          { label: "Ticket ID" },
        ],
      },
    ],
    actions: ["Search", "Clear", "Export in Excel"],
    table: { columns: ["ID", "Subject", "Sender", "Category", "Priority", "Status", "Assigned To", "Created At", "Action"] },
  },
}

export const requisitionScreens: Record<string, ScreenConfig> = {
  approvals: {
    title: "Requisitions",
    description: "Guard Approval By HO with Pending / Accepted / Rejected tabs.",
    tabs: ["Pending", "Accepted", "Rejected"],
    sections: [
      {
        title: "Guard Approval Filters",
        fields: [
          { label: "Secure Ops ID" },
          { label: "Name" },
          { label: "Current Status", type: "select" },
          { label: "Over Age", type: "select", options: ["Yes", "No"] },
          { label: "From Date", type: "date" },
          { label: "To Date", type: "date" },
        ],
      },
    ],
    actions: ["Search", "Approve", "Reject", "Export Excel"],
    table: { columns: ["Secure Ops ID", "Name", "Current Status", "Over Age", "Pic", "Requested At", "Action"] },
  },
}

export const auditScreens: Record<string, ScreenConfig> = {
  search: {
    title: "Audit Search",
    description: "System-wide activity tracking and compliance log.",
    sections: [
      {
        title: "Audit Filters",
        fields: [
          { label: "Date From", type: "date" },
          { label: "Date To", type: "date" },
          { label: "User Name" },
          { label: "Event", type: "select" },
          { label: "Module", type: "select" },
          { label: "IP Address" },
        ],
      },
    ],
    actions: ["Search", "Clear", "Export Excel"],
    table: { columns: ["Date", "User Name", "Event", "Module", "IP Address", "Description"] },
  },
}

export const payrollScreens: Record<string, ScreenConfig> = {
  operationsHub: {
    title: "Payroll Operations",
    description: "Frontend parity screen for payroll operational workflows from UI docs.",
    sections: [
      {
        title: "Operation Overview",
        fields: [
          { label: "Month", type: "month" },
          { label: "Region", type: "select" },
          { label: "Select Client", type: "select" },
          { label: "Branch", type: "select" },
        ],
      },
    ],
    actions: ["Search", "Clear"],
    table: { columns: ["Operation", "Month", "Region", "Client", "Branch", "Action"] },
  },
  reportsHub: {
    title: "Payroll Reports",
    description: "Export and analytics tools listed in payroll report submenu.",
    sections: [
      {
        title: "Export Set",
        fields: payrollReportExports.map((name) => ({ label: name, type: "checkbox" })),
      },
    ],
    actions: ["Run Selected Report", "Export"],
    table: { columns: ["Report", "Frequency", "Last Run", "Status", "Action"] },
  },
  settingsHub: {
    title: "Payroll Settings",
    description: "Payroll defaults, month initialize, and limits from UI docs.",
    tabs: ["Payroll Defaults", "Month Initialise", "Limits"],
    sections: [
      {
        title: "Payroll Defaults",
        fields: [
          { label: "Training School Fees", type: "number" },
          { label: "CWF", type: "number" },
          { label: "Age Threshold", type: "number" },
          { label: "Deployment Threshold", type: "number" },
        ],
      },
      {
        title: "Month Initialise",
        fields: [
          { label: "Current Month", type: "month" },
          { label: "Next Month", type: "month" },
          { label: "Unposted Regions", type: "select" },
        ],
      },
      {
        title: "Limits",
        fields: [
          { label: "Guard Age Limit", type: "number" },
          { label: "Mental Health Limit", type: "number" },
        ],
      },
    ],
    actions: ["Save Defaults", "Initialize Month", "Save Limits"],
    table: { columns: ["Setting Group", "Key", "Value", "Updated At"] },
  },
}

export const moduleHubScreens: Record<string, ScreenConfig> = {
  inventoryDashboard: {
    title: "Inventory Dashboard",
    description: "Asset dashboard with availability, issued, and remaining counts.",
    sections: [
      {
        title: "Dashboard Cards",
        fields: [
          { label: "Total Available", type: "number" },
          { label: "Issued", type: "number" },
          { label: "Remaining", type: "number" },
        ],
      },
    ],
    actions: ["Search", "Clear"],
    table: { columns: ["Product Type", "Total Available", "Issued", "Remaining"] },
  },
  reportsHub: {
    title: "Reports",
    description: "Frontend route hub for all documented report screens.",
    sections: [
      {
        title: "Report Hub",
        fields: [
          { label: "Date From", type: "date" },
          { label: "Date To", type: "date" },
          { label: "Region", type: "select" },
        ],
      },
    ],
    actions: ["Generate", "Export", "Clear"],
    table: { columns: ["Report", "Date Range", "Region", "Generated At", "Status"] },
  },
  importsHub: {
    title: "Imports",
    description: "Bulk operations hub for users, guards, clients, and inventory.",
    sections: [{ title: "Import Workflow", fields: [{ label: "Import Type", type: "select" }, { label: "Upload File" }] }],
    actions: ["Validate", "Import", "Clear"],
    table: { columns: ["Import Type", "Uploaded By", "Uploaded At", "Status", "Action"] },
  },
  ticketNew: {
    title: "Create Ticket",
    description: "Frontend-only ticket creation flow.",
    sections: [
      {
        title: "Ticket Form",
        fields: [
          { label: "Subject", required: true },
          { label: "Description", type: "textarea", required: true },
          { label: "Category", type: "select", required: true },
          { label: "Priority", type: "select", required: true },
          { label: "Assign To", type: "select" },
        ],
      },
    ],
    actions: ["Submit", "Reset"],
    table: { columns: ["Subject", "Category", "Priority", "Assign To", "Status"] },
  },
  clientPricing: {
    title: "Client Pricing",
    description: "Contractual pricing and billing configurations.",
    sections: [
      {
        title: "Pricing Configuration",
        fields: [
          { label: "Client", type: "select", required: true },
          { label: "Guard Type", type: "select", required: true },
          { label: "Rate", type: "number", required: true },
          { label: "Effective From", type: "date" },
        ],
      },
    ],
    actions: ["Save", "Update", "Clear"],
    table: { columns: ["Client", "Guard Type", "Rate", "Effective From", "Action"] },
  },
  systemSettings: {
    title: "System Settings",
    description: "Frontend placeholder for global system settings.",
    sections: [
      {
        title: "General",
        fields: [
          { label: "Application Name" },
          { label: "Timezone", type: "select" },
          { label: "Default Currency", type: "select" },
        ],
      },
    ],
    actions: ["Save Settings", "Clear"],
    table: { columns: ["Setting", "Value", "Updated At"] },
  },
}
