import { test, expect } from "@playwright/test"
import {
  LIFECYCLE,
  endActiveDeploymentsForGuard,
  ensureLifecycleContract,
  ensureSupervisorAssigned,
} from "./helpers/lifecycle-fixtures"
import { clickDeploySave, fillDeployForm } from "./helpers/deploy-form"
import { fetchAttendanceForGuard, todayIsoDate } from "./helpers/attendance"

/**
 * Verifies the auto-attendance side-effect of POST /api/deployments:
 * after an ACTIVE deployment is created for a guard, an Attendance row
 * for today must exist, be flagged isAutoGenerated=true, link back to
 * the new deployment, and indicate PRESENT (or double-duty variant).
 *
 * Prereq: `LIFECYCLE_E2E_SEED_EXECUTE=true node scripts/seed-guard-lifecycle-e2e.mjs`.
 */
test.describe("Deployment — auto-attendance side effect", () => {
  test("creating a deployment generates today's Attendance row for the guard", async ({
    page,
  }) => {
    // Fixture setup — mirror the happy-path spec.
    await endActiveDeploymentsForGuard(page, LIFECYCLE.guards.assigned.parwestId)
    await ensureSupervisorAssigned(page, LIFECYCLE.guards.assigned.parwestId)
    await ensureLifecycleContract(page)

    // Drive the deploy form (shared helper).
    await fillDeployForm(page, { guardParwestId: LIFECYCLE.guards.assigned.parwestId })

    const createResponse = page.waitForResponse(
      (r) => r.url().endsWith("/api/deployments") && r.request().method() === "POST",
      { timeout: 20_000 }
    )
    await clickDeploySave(page)
    const res = await createResponse

    const createdBody = (await res.json().catch(() => ({}))) as {
      id?: string
      guardId?: string
      status?: string
      message?: string
    }
    expect(
      res.status(),
      `POST /api/deployments failed: ${createdBody?.message ?? JSON.stringify(createdBody)}`
    ).toBe(201)
    expect(createdBody.id, "deployment id missing from POST response").toBeTruthy()
    expect(createdBody.guardId, "guardId missing from POST response").toBeTruthy()
    expect(createdBody.status).toBe("ACTIVE")

    const deploymentId = createdBody.id!
    const guardId = createdBody.guardId!
    const today = todayIsoDate()

    // Fetch attendance rows for this guard for today.
    const { ok, status, bodyText, rows } = await fetchAttendanceForGuard(
      page.request,
      guardId,
      today
    )
    expect(
      ok,
      `GET /api/attendance failed (${status}). Body: ${bodyText}`
    ).toBe(true)

    const dump = `rows=${JSON.stringify(rows)} rawBody=${bodyText}`
    expect(rows.length, `expected ≥1 attendance row for today. ${dump}`).toBeGreaterThanOrEqual(1)

    const todaysRow = rows.find((r) => {
      const rDate = new Date(r.date)
      const key = `${rDate.getFullYear()}-${String(rDate.getMonth() + 1).padStart(2, "0")}-${String(rDate.getDate()).padStart(2, "0")}`
      return key === today && r.guardId === guardId
    })
    expect(todaysRow, `no attendance row matches today (${today}) + guardId (${guardId}). ${dump}`).toBeTruthy()

    // status is always PRESENT on auto-generate (attendanceType may be PRESENT or DOUBLE_DUTY_*).
    expect(todaysRow!.status, `unexpected status. ${dump}`).toBe("PRESENT")
    expect(
      todaysRow!.attendanceType,
      `expected attendanceType to be PRESENT or DOUBLE_DUTY_*. ${dump}`
    ).toMatch(/^(PRESENT|DOUBLE_DUTY_DAY|DOUBLE_DUTY_NIGHT)$/)
    expect(todaysRow!.isAutoGenerated, `isAutoGenerated should be true. ${dump}`).toBe(true)
    expect(
      todaysRow!.deploymentId,
      `deploymentId should link to created deployment (${deploymentId}). ${dump}`
    ).toBe(deploymentId)
  })
})
