// Each definition file calls registerReport() at import time.
// Add new reports by importing them here.
import "./guards/hired"
import "./guards/terminated"
import "./guards/verification"
import "./guards/deployment-status"
import "./guards/attendance"
import "./guards/salary"
import "./guards/expiring-docs"
import "./clients/enrolled"
import "./clients/branches-opened"
import "./clients/active-inactive"
import "./clients/branch-capacity"
import "./clients/increase-decrease"
import "./deployments/current"
import "./deployments/history"
import "./deployments/day-night"
import "./deployments/unassigned"
import "./deployments/short-term"
import "./financial/salary-export"
import "./financial/unpaid-salary"
import "./financial/loans"
import "./financial/clearance"
import "./financial/invoices"
import "./financial/invoice-errors"
import "./inventory/total"
import "./inventory/by-status"
import "./inventory/by-region"
import "./inventory/issued-by-guard"
import "./inventory/condemned"
import "./other/complaints"
import "./other/ai-summary"

export {}
