import { NextResponse } from "next/server"
import { prisma } from "@/lib/db"
import { auth } from "@/lib/auth"
import { forbidden, unauthorized } from "@/lib/api/response"
import { hasAction } from "@/lib/api/permissions"

type Params = { params: Promise<{ id: string }> }

/**
 * POST /api/guards/[id]/attendance/auto-generate
 *
 * Generates missing PRESENT attendance records for all active deployments of
 * the guard, from deploymentDate up to and including today.
 * Existing records are never overwritten (skipDuplicates).
 *
 * Returns: { generated: number }
 */
export async function POST(_req: Request, { params }: Params) {
  const session = await auth()
  if (!session) return unauthorized()
  if (!hasAction(session, "GUARDS", "CREATE")) return forbidden("Access denied.")

  const { id: guardId } = await params

  try {
    // Get all active deployments for this guard
    const activeDeployments = await prisma.deployment.findMany({
      where: { guardId, status: "ACTIVE" },
      include: {
        client: { select: { id: true, name: true } },
      },
    })

    if (activeDeployments.length === 0) {
      return NextResponse.json({ generated: 0 })
    }

    // Get existing attendance dates for this guard (to avoid re-generating)
    const existingRecords = await prisma.attendance.findMany({
      where: { guardId },
      select: { date: true },
    })

    const existingDateSet = new Set<string>(
      existingRecords.map((r) => {
        const d = new Date(r.date)
        return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`
      })
    )

    const today = new Date()
    today.setHours(0, 0, 0, 0)

    const toCreate: {
      guardId: string
      date: Date
      status: string
      shiftType: string | null
      attendanceType: string
      deploymentId: string
      clientId: string
      clientName: string
      isAutoGenerated: boolean
    }[] = []

    for (const dep of activeDeployments) {
      const start = new Date(dep.deploymentDate)
      start.setHours(0, 0, 0, 0)

      const current = new Date(start)
      while (current <= today) {
        const key = `${current.getFullYear()}-${String(current.getMonth() + 1).padStart(2, "0")}-${String(current.getDate()).padStart(2, "0")}`

        if (!existingDateSet.has(key)) {
          toCreate.push({
            guardId,
            date: new Date(current),
            status: "PRESENT",
            shiftType: dep.shiftType ?? null,
            attendanceType: "PRESENT",
            deploymentId: dep.id,
            clientId: dep.clientId,
            clientName: dep.client.name,
            isAutoGenerated: true,
          })
          // Add to set so we don't duplicate if guard has multiple active deployments for same day
          existingDateSet.add(key)
        }

        current.setDate(current.getDate() + 1)
      }
    }

    if (toCreate.length === 0) {
      return NextResponse.json({ generated: 0 })
    }

    // Batch insert in chunks to avoid hitting DB limits
    const CHUNK = 500
    let total = 0
    for (let i = 0; i < toCreate.length; i += CHUNK) {
      const result = await prisma.attendance.createMany({
        data: toCreate.slice(i, i + CHUNK),
        skipDuplicates: true,
      })
      total += result.count
    }

    return NextResponse.json({ generated: total })
  } catch (error) {
    console.error(`[POST /api/guards/${guardId}/attendance/auto-generate] failed:`, error)
    return NextResponse.json({ generated: 0, error: "Failed to auto-generate attendance" }, { status: 500 })
  }
}