export type GuardLooseRow = Record<string, unknown>

export type AttendanceRecord = {
  date: string | Date
  status: string
  shift?: string
  attendanceType?: string   // PRESENT | DOUBLE_DUTY_DAY | DOUBLE_DUTY_NIGHT | EXTRA_DUTY
  clientId?: string
  clientName?: string
  hours?: number | string
  overtime?: number | string
  reason?: string | null
  deploymentId?: string
  isAutoGenerated?: boolean
}

export type AttendanceSummary = {
  totalDays?: number | string
  present?: number | string
  absent?: number | string
  overtime?: number | string
}

export type PaidSalaryRecord = {
  month: string
  amount: number
  deductions: number
  netAmount: number
  method: string
  paidOn: string
  status: string
}

export type NearestRelative = {
  name?: string
  fatherName?: string
  relation?: string
  profession?: string
  cnic?: string
  cnicIssueDate?: string
  contact?: string
  address?: string
}

export type FamilyMember = {
  name?: string
  relation?: string
  age?: string
  profession?: string
  address?: string
  childCnic?: string
  childAge?: string
  childDob?: string
}

export type GuardTabModel = {
  id?: string
  parwestId?: string
  name?: string
  cnic?: string
  status?: string
  dateOfBirth?: string | Date | null
  joiningDate?: string | Date | null
  age?: number | null
  fatherName?: string | null
  motherName?: string | null
  religion?: string | null
  maritalStatus?: string | null
  education?: string | null
  nationality?: string | null
  nextOfKin?: string | null
  profileIntroducer?: string | null
  phone?: string | null
  email?: string | null
  emergencyContact?: string | null
  additionalContactNumbers?: string | null
  phoneSecondary?: string | null
  addressPermanent?: string | null
  addressCurrent?: string | null
  regionalOffice?: string | { name?: string | null } | null
  region?: GuardLooseRow | null
  managerName?: string | null
  enrolledBy?: string | null
  joiningAge?: number | null
  isExService?: boolean
  nearestRelatives?: NearestRelative[]
  // General extras
  sect?: string | null
  cast?: string | null
  bloodGroup?: string | null
  policeStation?: string | null
  cnicIssueDate?: string | Date | null
  cnicExpiryDate?: string | Date | null
  salary?: number | null
  designation?: string | null
  // Previous employment
  exServiceType?: string | null
  exServiceRank?: string | null
  exServiceRegiment?: string | null
  exServiceRegistrationNo?: string | null
  exServiceUnit?: string | null
  exServicePeriod?: string | null
  exServiceYears?: number | null
  exServiceMonths?: number | null
  exServiceOtherLabel?: string | null
  dateOfEnrollment?: string | Date | null
  dateOfDischarge?: string | Date | null
  exServiceRemarks?: string | null
  // Address contacts
  currentAddressContact?: string | null
  permanentAddressContact?: string | null
  // Education extras
  passingYear?: string | null
  educationInstitute?: string | null
  // Introducer
  introducerName?: string | null
  introducerCnic?: string | null
  introducerAddress?: string | null
  introducerContact?: string | null
  // Physical
  height?: string | null
  weight?: string | null
  eyeColor?: string | null
  hairColor?: string | null
  disability?: string | null
  identificationMark?: string | null
  // Previous employments (new multi-entry)
  previousEmployments?: Array<{
    type?: string
    isExService?: boolean
    rank?: string
    registrationNo?: string
    unit?: string
    dateOfEnrollment?: string | null
    dateOfDischarge?: string | null
    years?: string | number | null
    months?: string | number | null
    remarks?: string | null
  }>
  // Family
  familyMembers?: FamilyMember[]
  // Enrollment metadata
  createdAt?: string | Date | null
  // Age approval
  ageApprovalRequired?: boolean
  ageApprovalStatus?: string | null
  attachments?: GuardLooseRow[]
  attendance?: AttendanceRecord[]
  attendanceSummary?: AttendanceSummary
  inventory?: GuardLooseRow[]
  salaries?: PaidSalaryRecord[]
  deployments?: GuardLooseRow[]
  courses?: GuardLooseRow[]
  verifications?: GuardLooseRow[]
  pledgedDocuments?: GuardLooseRow[]
  bankDetails?: GuardLooseRow
  residenceHistory?: GuardLooseRow[]
  ojtTrainings?: GuardLooseRow[]
  storeInventory?: GuardLooseRow[]
  serviceHistory?: GuardLooseRow[]
  insurance?: GuardLooseRow[]
  statusHistory?: GuardLooseRow[]
  pbaDocuments?: GuardLooseRow[]
}
