import type { APIRequestContext } from "@playwright/test"

/**
 * Minimal shape of an Attendance row as returned by GET /api/attendance.
 * Only fields this spec asserts on are listed — the real payload has more.
 */
export type AttendanceRow = {
  id: string
  guardId: string
  date: string
  status: string
  shiftType: string | null
  attendanceType: string | null
  deploymentId: string | null
  isAutoGenerated: boolean
}

/** Today in YYYY-MM-DD in the runner's local timezone (matches server's midnight normalization). */
export function todayIsoDate(): string {
  const d = new Date()
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`
}

/** Fetch attendance rows for a guard on a specific date. The server now
 *  normalizes startDate/endDate to local midnight, so exact-day queries
 *  reliably match rows written with `setHours(0,0,0,0)`.
 */
export async function fetchAttendanceForGuard(
  req: APIRequestContext,
  guardId: string,
  date: string
): Promise<{ ok: boolean; status: number; bodyText: string; rows: AttendanceRow[] }> {
  const url = `/api/attendance?guardId=${encodeURIComponent(guardId)}&startDate=${date}&endDate=${date}`
  const res = await req.get(url)
  const bodyText = await res.text()
  let rows: AttendanceRow[] = []
  try {
    const parsed = JSON.parse(bodyText) as AttendanceRow[] | { data?: AttendanceRow[] }
    rows = Array.isArray(parsed) ? parsed : parsed.data ?? []
  } catch {
    rows = []
  }
  return { ok: res.ok(), status: res.status(), bodyText, rows }
}
