import type { APIRequestContext } from "@playwright/test"

/**
 * Minimal shape of an Attendance row as returned by GET /api/attendance.
 * Only fields this spec asserts on are listed — the real payload has more.
 */
export type AttendanceRow = {
  id: string
  guardId: string
  date: string
  status: string
  shiftType: string | null
  attendanceType: string | null
  deploymentId: string | null
  isAutoGenerated: boolean
}

/** Today in YYYY-MM-DD in the runner's local timezone (matches server's midnight normalization). */
export function todayIsoDate(): string {
  const d = new Date()
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`
}

/** Fetch attendance rows for a guard. Window is ±1 day to defuse timezone
 *  skew: the server writes date = local midnight via `setHours(0,0,0,0)`, but
 *  the GET filter parses `new Date(startDate)` as UTC midnight, so an exact
 *  startDate=endDate=today query drops the row in any non-UTC timezone.
 */
export async function fetchAttendanceForGuard(
  req: APIRequestContext,
  guardId: string,
  date: string
): Promise<{ ok: boolean; status: number; bodyText: string; rows: AttendanceRow[] }> {
  const d = new Date(`${date}T00:00:00`)
  const start = new Date(d)
  start.setDate(start.getDate() - 1)
  const end = new Date(d)
  end.setDate(end.getDate() + 1)
  const iso = (x: Date) =>
    `${x.getFullYear()}-${String(x.getMonth() + 1).padStart(2, "0")}-${String(x.getDate()).padStart(2, "0")}`
  const url = `/api/attendance?guardId=${encodeURIComponent(guardId)}&startDate=${iso(start)}&endDate=${iso(end)}`
  const res = await req.get(url)
  const bodyText = await res.text()
  let rows: AttendanceRow[] = []
  try {
    const parsed = JSON.parse(bodyText) as AttendanceRow[] | { data?: AttendanceRow[] }
    rows = Array.isArray(parsed) ? parsed : parsed.data ?? []
  } catch {
    rows = []
  }
  return { ok: res.ok(), status: res.status(), bodyText, rows }
}
